name: simple_dart_num_field
description: NumField Component
version: 0.0.2
repository: https://github.com/simple-dart/num_field
platforms:
  web:

environment:
  sdk: '>=2.18.0 <3.0.0'


dependencies:
  simple_dart_ui_core: ^0.0.2
